# Generated by Django 3.0.6 on 2020-05-13 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cod_sale', models.CharField(max_length=10, verbose_name='id venta')),
                ('voucher', models.CharField(max_length=30, verbose_name='Tipo de comprobante')),
                ('client', models.CharField(max_length=15, verbose_name='Documento Cliente')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Monto Recibido')),
                ('anulate', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_user', to=settings.AUTH_USER_MODEL, verbose_name='cajero que emitio')),
            ],
            options={
                'verbose_name': 'Comprobante Emitida',
                'verbose_name_plural': 'Compobantes de pago emitidas',
            },
        ),
        migrations.CreateModel(
            name='CloseBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_close', models.DateTimeField(verbose_name='Fecha de Cierre')),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad de productos vendidos')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total en ventas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_user', to=settings.AUTH_USER_MODEL, verbose_name='cajero')),
            ],
            options={
                'verbose_name': 'Cierre Caja',
                'verbose_name_plural': 'Cirres de Caja',
            },
        ),
    ]
