# Generated by Django 3.0.6 on 2020-05-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
