# Generated by Django 3.0.6 on 2020-05-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_carshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='barcode',
            field=models.CharField(default='1', max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
