# Generated by Django 3.0.6 on 2020-05-15 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_carshop_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carshop',
            name='price_sale',
        ),
    ]
