# Generated by Django 3.0.6 on 2020-05-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_remove_carshop_price_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carshop',
            options={'ordering': ['-created'], 'verbose_name': 'Carrito de compras', 'verbose_name_plural': 'Carrito de compras'},
        ),
        migrations.AddField(
            model_name='sale',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
