# Generated by Django 3.0.6 on 2020-05-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_auto_20200515_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='anulate',
            field=models.BooleanField(default=False, verbose_name='Venta Anulada'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='close',
            field=models.BooleanField(default=False, verbose_name='Venta cerrada'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_sale', to='venta.Sale', verbose_name='Codigo de Venta'),
        ),
    ]
