# Generated by Django 3.0.6 on 2020-05-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_sale',
            field=models.PositiveIntegerField(default=0, verbose_name='numero de ventas'),
        ),
    ]
